"""Add is_threshold_breach to portfolio risk snapshots

Revision ID: e2983d92d71d
Revises: d82628b3a5e9
Create Date: 2025-08-27 16:32:26.889743

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2983d92d71d'
down_revision: Union[str, Sequence[str], None] = 'd82628b3a5e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'portfolio_risk_snapshots', 
        sa.Column('is_threshold_breach', sa.Boolean(), nullable=False, server_default='false')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_portfolio_risk_snapshots_is_threshold_breach'), table_name='portfolio_risk_snapshots')
    op.drop_column('portfolio_risk_snapshots', 'is_threshold_breach')
    # ### end Alembic commands ###
